languageCode = "en"
languageName = "English"
weight = 1
title = "Wind Tavern"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/bird_house.png"
  description = "Wanna have a cup of milk?"
  copyright = "© 2024 Wind Tavern"

[params.author]
  name = "Shu"
  email = "windtavern@outlook.com"
  image = "img/canary_bird.png"
  # headline = "Welcome! This is a tavern but only offer milk."
  bio = "Me embraced wind."
  # links = [
  #   { x-twitter = "https://twitter.com/windtavern" },
  #   { github = "https://github.com/windtavern" },
  # ]