# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "ocean"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

replyByEmail = false

mainSections = ["docs"]
# robots = ""

disableImageOptimization = false
disableTextInHeader = false
# backgroundImageWidth = 1200

defaultBackgroundImage = "/img/background.svg"
defaultFeaturedImage = "/img/pet_bed.svg"

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = true

[header]
  layout = "fixed" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[footer]
  showMenu = false
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile" # valid options: page, profile, hero, card, background, custom
  # homepageImage = "/img/iceland.jpg" # used in: hero, and card
  showRecent = true
  showRecentItems = 3
  showMoreLink = true
  showMoreLinkDest = "docs"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = false # only used when layout equals background

[article]
  showDate = true
  showViews = true
  showLikes = true
  showDateOnlyInArticle = false
  showDateUpdated = true
  showAuthor = true
  # showAuthorBottom = false
  showHero = false
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  editAppendPath = false
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 9
  showTaxonomies = true 
  showAuthorsBadges = true 
  showWordCount = true
  sharingLinks = false
  showZenMode = true
  showComments = true

[list]
  showHero = false
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = false
  showSummary = false
  showViews = true
  showLikes = true
  showTableOfContents = false
  showCards = false
  orderByWeight = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  constrainItemsWidth = true

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  showHero = false
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  cardView = false

[term]
  showHero = false
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  
[firebase]
  apiKey = "AIzaSyBz__1jf1Zyyd-I5TMCdttyRpuT7DDtCqg"
  authDomain = "wind-tavern.firebaseapp.com"
  projectId = "wind-tavern"
  storageBucket = "wind-tavern.appspot.com"
  messagingSenderId = "275319097264"
  appId = "1:275319097264:web:84a762b4636afcdcebf875"
  measurementId = "G-7MLTD57XWL"

# [umamiAnalytics]
#   websiteid = ""
#   domain = ""
#   dataDomains = ""
#   enableTrackEvent = false

# [verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""

[googleAnalytics]
  googleAnalytics = "G-LTS370N4XM"


